- name: Autenticación en Heroku
  env:
    HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
  run: |
    echo $HEROKU_API_KEY | heroku auth:token
    heroku whoami

- name: Desplegar en Heroku
  env:
    HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
    HEROKU_APP_NAME: "microservicio-python-demo"
  run: |
    heroku git:remote -a $HEROKU_APP_NAME
    git push heroku main
